Lesson19
Zokmi4/tms-git pull request #5
Opened 2024-07-10 17:21 UTC by Zokmi4

@rzmv

2024-07-28 16:24 UTC, rzmv requested changes
Немного правок, в целом супер

2024-07-28 16:24 UTC, rzmv commented on dz19.yaml
> +        state: reloaded
Кирпич

2024-07-28 16:24 UTC, rzmv commented on dz19.version2.0.yaml
> +      notify: restart postgresql
А зачем рестартить после установки?

2024-07-28 16:24 UTC, rzmv commented on dz19.version2.0.yaml
> +    - name: Install Nginx
Можно поставить сразу 2 пакета: nginx & postgresql

2024-07-28 16:24 UTC, rzmv commented on dz19.version2.0.yaml
> +        state: reloaded
Кирпич

2024-07-28 16:24 UTC, rzmv commented on dz19.version2.0.yaml
> +        force: yes
Почему с force?

2024-07-29 16:23 UTC, Zokmi4 commented on dz19.version2.0.yaml
> +      notify: restart postgresql
Можно и не рестартить в целом, просто захотелось написать если честно)

2024-07-29 16:24 UTC, Zokmi4 commented on dz19.version2.0.yaml
> +    - name: Install Nginx
В тот момент, я не был уверен в своих возможностях)

2024-07-29 16:26 UTC, Zokmi4 commented on dz19.version2.0.yaml
> +        force: yes
Т.к nginx стоял уже на системе - просто удалит и перезапишет файлы

2024-07-29 20:44 UTC, rzmv approved these changes

2024-07-30 03:07 UTC, merged